function [date, hour, T, rh, Td, wspd, wdir, gust, gust_dir, P] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [DATE, HOUR, T, RH, TD, WSPD, WDIR, GUST, GUST_DIR, P] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [DATE, HOUR, T, RH, TD, WSPD, WDIR, GUST, GUST_DIR, P] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [date, hour, T, rh, Td, wspd, wdir, gust, gust_dir, P] = importfile("/Users/aevan/Documents/SALTON/DUST_CASES/20200222/Davis/20200222.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2020 15:25:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 30);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["date", "hour", "T", "Var4", "Var5", "rh", "Td", "wspd", "wdir", "Var10", "gust", "gust_dir", "Var13", "Var14", "Var15", "P", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30"];
opts.SelectedVariableNames = ["date", "hour", "T", "rh", "Td", "wspd", "wdir", "gust", "gust_dir", "P"];
opts.VariableTypes = ["datetime", "string", "double", "string", "string", "double", "double", "double", "categorical", "string", "double", "categorical", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, 1, "InputFormat", "MM/dd/yy");
opts = setvaropts(opts, [2, 4, 5, 10, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 4, 5, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
date = tbl.date;
hour = tbl.hour;
T = tbl.T;
rh = tbl.rh;
Td = tbl.Td;
wspd = tbl.wspd;
wdir = tbl.wdir;
gust = tbl.gust;
gust_dir = tbl.gust_dir;
P = tbl.P;
end