function out = readBPSTA(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BPSTA20202 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  BPSTA20202 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  BPSTA20202 = importfile("/Users/aevan/Documents/SALTON/DUST_CASES/CARB/BPSTA_2020-2.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jun-2020 09:11:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["site", "date", "start_hour", "pressure", "variable", "units", "quality", "prelim", "met_source", "obs_type", "minutes", "name"];
opts.VariableTypes = ["double", "datetime", "double", "double", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "double", "categorical"];
opts = setvaropts(opts, 2, "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, [5, 6, 8, 9, 10, 12], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
out = readtable(filename, opts);

end